version: '3'
services:
  webserver:
    image: my_airflow_image
    ports:
      - "8080:8080"
    environment:
      - LOAD_EX=y
      - EXECUTOR=LocalExecutor
    volumes:
      - ./dags:/usr/local/airflow/dags
      - ./modules:/usr/local/airflow/modules
      - ./requirements.txt:/usr/local/airflow/requirements.txt
      - ./.env:/usr/local/airflow/.env
    command: ["airflow", "webserver"]
  scheduler:
    image: my_airflow_image
    environment:
      - EXECUTOR=LocalExecutor
    volumes:
      - ./dags:/usr/local/airflow/dags
      - ./modules:/usr/local/airflow/modules
      - ./requirements.txt:/usr/local/airflow/requirements.txt
      - ./.env:/usr/local/airflow/.env
    command: ["airflow", "scheduler"]
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - "5432:5432"
    volumes:
      - postgres_db_volume:/var/lib/postgresql/data
volumes:
  postgres_db_volume:
