from modules.data_from_api import extract_crypto_data
from modules.data_transformation import transform_data
from modules.upload_rs import load_data_to_redshift, load_data_from_csv
from modules.remove_atypical_values import remove_outliers
from modules.alerting import check_and_send_alert, send_alert
from modules.csv_adquisition import load_data_from_csv